apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  labels:
    {{- include "metrics-server.labels" . | nindent 4 }}
  name: v1beta1.metrics.k8s.io
spec:
  group: metrics.k8s.io
  groupPriorityMinimum: 100
  insecureSkipTLSVerify: true
  service:
    name: {{ include "metrics-server.fullname" . }}
    namespace: {{ .Release.Namespace }}
  version: v1beta1
  versionPriority: 100
