apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "metrics-server.fullname" . }}
  labels:
    {{- include "metrics-server.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "metrics-server.selectorLabels" . | nindent 6 }}
