apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: {{ include "postgres.fullname" . }}-cluster
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  teamId: "acid"
  numberOfInstances: {{ .Values.replicaCount }}
  spiloRunAsUser: 1000
  spiloRunAsGroup: 1000
  enableMasterLoadBalancer: false
  enableReplicaLoadBalancer: false
  users:
    pgadmin:  # database owner
      - superuser
      - createdb
    foo_user: []  # role for application foo
  databases:
    foo: pgadmin  # dbname: owner
  postgresql:
    version: {{ .Values.postgresql.version | quote }}
  volume:
    size: {{ .Values.postgresql.volume.size }}
    storageClass: {{ .Values.postgresql.volume.storageClass }}
